routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login');

Auth::routes();

Route::get('patients','HomeController@patients')->middleware('doctor')->name('patients');
Route::get('labrep','HomeController@lab')->middleware('labtech')->name('labtech');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('print/{id}',"HomeController@print")->name('print');

Route::resource('users','UserController')->middleware('admin');

Route::resource('information','informationController')->except(['destroy'])->middleware('nurse');

Route::name('vitalsign.')->prefix('vitalsign/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});

Route::name('phyexam.')->prefix('phyexam/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','PeController@create')->name('create');
	Route::post('store/{id}','PeController@store')->name('store');
	Route::get('edit/{id}','PeController@edit')->name('edit');
	Route::patch('update/{id}','PeController@update')->name('update');
});

Route::name('dental.')->prefix('dental/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','DentalController@create')->name('create');
	Route::post('store/{id}','DentalController@store')->name('store');
	Route::get('edit/{id}','DentalController@edit')->name('edit');
	Route::patch('update/{id}','DentalController@update')->name('update');
});

Route::name('labreport.')->prefix('lab/')->middleware('labtech')->group(function(){
	Route::get('create/{id}','LabReportController@create')->name('create');
	Route::post('store/{id}','LabReportController@store')->name('store');
	Route::get('edit/{id}','LabReportController@edit')->name('edit');
	Route::patch('update/{id}','LabReportController@update')->name('update');
	Route::view('upload/{id}','lab/upload')->name('upload');
});
Route::name('feedback.')->prefix('final')->middleware('doctor')->group(function(){
	Route::get('create/{id}','FeedbackController@create')->name('create');
	Route::post('store/{id}','FeedbackController@store')->name('store');
	// Route::get('edit/{id}','DentalController@edit')->name('edit');
	// Route::patch('update/{id}','DentalController@update')->name('update');
});
Route::get('labresult/{id}','LabReportController@edit')->middleware('doctor')->name('labresult.view');
Route::patch('labresult/{id}','LabReportController@update')->middleware('doctor')->name('labresult.update');


	Route::get('upload','LabReportController@upload_view')->name('upload');
	Route::get('upload/{id}','LabReportController@select')->middleware('labtech')->name('upload.edit');
	Route::get('search/{id}/upload','LabReportController@viewImage')->name('upload.search');
	Route::post('upload/{id}/save','LabReportController@saveimage')->middleware('labtech')->name('upload.save');
Route::get('admin/patients','UserController@patients')->middleware('admin')->name('patients.admin');
Route::get('admin/patient/delete/{id}','UserController@deletePatient')->middleware('admin')->name('admin.delete');
Route::get('admin/logs','HomeController@logs')->middleware('admin')->name('logs');
Route::get('settings','HomeController@view_settings')->name('settings');
Route::PATCH('password/update/{id}','HomeController@password')->name('password.update');
Route::get('employee/update/{id}','HomeController@employee')->name('employee.password');
Route::PATCH('employee/reset/{id}','HomeController@password')->name('employee.password.update');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto mt-5">
            <div class="card card-default">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @include('shared.alerts')
                    <div class="col-12">
                         <div class="text-center">
                            <h5>Welcome to St. Rita Clinic</h5>
                            <img src="{{ asset('image/logo.jpg') }}">
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/lab.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-dark mt-4">
	  <div class="card-header">Patients
	</div>
	  <div class="card-body text-dark">
		<table class="table " id="myTable" >
		  <thead class="thead-inverse card-text">
		      <th>#</th>
		      <th>Name</th>
		      <th>Lab Test</th>
		      <th>Date Created</th>
		  </thead>
		  <tbody>
		    @include('shared.alerts')
		    @foreach($patients as $patient)
		    <tr>
		      	<td>{{ $patient->id }}</td>
		      	<td>{{ $patient->lastname }} {{ $patient->firstname }}, {{ $patient->middlename }}</td>
			    <td>
			    	@if($patient->lab->isEmpty())
			    	New <a href="{{ route('labreport.create',['id' => $patient->id]) }}">Record</a>
			    	@else
			    	<a href="{{ route('labreport.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
			    	@endif
			    </td>
			    <td>{{ $patient->created_at->format('m-d-Y') }}</td>
		    </tr>
		    @endforeach
		  </tbody>
		</table>
	  </div>
</div>
</div>
@endsection

resources/views/logs.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-dark mt-4">
	  <div class="card-header">Activity Log
	</div>
	  <div class="card-body text-dark">
		<table class="table " id="myTable" >
		  <thead class="thead-inverse card-text">
		  	<th>ID</th>
		  	<th>User</th>
		  	<th>Action</th>
		  	<th>Date Created</th>
		  </thead>
		  <tbody>
		  	@foreach($logs as $log)
		  	<tr>
		  		<td>{{ $log->id }}</td>
		  		<td>{{ $log->employee['0']->name }}</td>
		  		<td>{{ $log->action }}</td>
		  		<td>{{ $log->created_at }}</td>
		  	</tr>
		  	@endforeach
		  </tbody>
		</table>
	</div>
	</div>
</div>
@endsection

resources/views/patients.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
	<div class="card border-dark mt-4">
	  <div class="card-header">Patients
	</div>
	  <div class="card-body text-dark">
		<table class="table " id="myTable" >
		  <thead class="thead-inverse card-text">
		      <th>#</th>
		      <th>Name</th>
		      <th>Vital Sign</th>
		      <th>Dental Checkup</th>
		      <th>Physical Examination</th>
		      <th>Lab Result</th>
  		      <th>View</th>
		      <th>Date Created</th>
		  </thead>
		  <tbody>
		    @include('shared.alerts')
		    @foreach($patients as $patient)
		    <tr>
		      	<td>{{ $patient->id }}</td>
		      	<td>{{ $patient->lastname }} {{ $patient->firstname }}, {{ $patient->middlename }}</td>
			    <td>
			    	@if($patient->vitalsign->isEmpty())
			    	New <a href="{{ route('vitalsign.create',['id' => $patient->id]) }}">Record</a>
			    	@else
			    	<a href="{{ route('vitalsign.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
			    	@endif
			    </td>
			    <td>
			    	@if($patient->dental->isEmpty())
			    	New <a href="{{ route('dental.create',['id' => $patient->id]) }}">Record</a>
			    	@else
			    	<a href="{{ route('dental.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
			    	@endif
			    </td>
			    <td>
			    	@if($patient->phyexam->isEmpty())
			    	New <a href="{{ route('phyexam.create',['id' => $patient->id]) }}">Record</a>
			    	@else
			    	<a href="{{ route('phyexam.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
			    	@endif
			    </td>
			    <td>
			    	@if($patient->lab->isEmpty())
			    	Pending.
			    	@else
			    	<a href="{{ route('feedback.create',['id' => $patient->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
			    	@endif
			    </td>
			    <td>
					@if($patient->lab->isEmpty() || $patient->phyexam->isEmpty() || $patient->dental->isEmpty() )
						Incomplete Test.
					@else
						<a href="{{ route('print',['id' => $patient->id]) }}" class="btn btn-info btn-sm"><i class="fa fa-search"></i></a>
					@endif
			    </td>
			    <td>{{ $patient->created_at->format('m-d-Y') }}</td>
		    </tr>
		    @endforeach
		  </tbody>
		</table>
	  </div>
</div>
</div>
@endsection