routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login');

Auth::routes();

Route::get('patients','HomeController@patients')->middleware('doctor')->name('patients');
Route::get('labrep','HomeController@lab')->middleware('labtech')->name('labtech');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('print/{id}',"HomeController@print")->name('print');

Route::resource('users','UserController')->middleware('admin');

Route::resource('information','informationController')->except(['destroy'])->middleware('nurse');

Route::name('vitalsign.')->prefix('vitalsign/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});

Route::name('phyexam.')->prefix('phyexam/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','PeController@create')->name('create');
	Route::post('store/{id}','PeController@store')->name('store');
	Route::get('edit/{id}','PeController@edit')->name('edit');
	Route::patch('update/{id}','PeController@update')->name('update');
});

Route::name('dental.')->prefix('dental/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','DentalController@create')->name('create');
	Route::post('store/{id}','DentalController@store')->name('store');
	Route::get('edit/{id}','DentalController@edit')->name('edit');
	Route::patch('update/{id}','DentalController@update')->name('update');
});

Route::name('labreport.')->prefix('lab/')->middleware('labtech')->group(function(){
	Route::get('create/{id}','LabReportController@create')->name('create');
	Route::post('store/{id}','LabReportController@store')->name('store');
	Route::get('edit/{id}','LabReportController@edit')->name('edit');
	Route::patch('update/{id}','LabReportController@update')->name('update');
	Route::view('upload/{id}','lab/upload')->name('upload');
});
Route::name('feedback.')->prefix('final')->middleware('doctor')->group(function(){
	Route::get('create/{id}','FeedbackController@create')->name('create');
	Route::post('store/{id}','FeedbackController@store')->name('store');
	// Route::get('edit/{id}','DentalController@edit')->name('edit');
	// Route::patch('update/{id}','DentalController@update')->name('update');
});
Route::get('labresult/{id}','LabReportController@edit')->middleware('doctor')->name('labresult.view');
Route::patch('labresult/{id}','LabReportController@update')->middleware('doctor')->name('labresult.update');


	Route::get('upload','LabReportController@upload_view')->name('upload');
	Route::get('upload/{id}','LabReportController@select')->middleware('labtech')->name('upload.edit');
	Route::get('search/{id}/upload','LabReportController@viewImage')->name('upload.search');
	Route::post('upload/{id}/save','LabReportController@saveimage')->middleware('labtech')->name('upload.save');
Route::get('admin/patients','UserController@patients')->middleware('admin')->name('patients.admin');
Route::get('admin/patient/delete/{id}','UserController@deletePatient')->middleware('admin')->name('admin.delete');
Route::get('admin/logs','HomeController@logs')->middleware('admin')->name('logs');
Route::get('settings','HomeController@view_settings')->name('settings');
Route::PATCH('password/update/{id}','HomeController@password')->name('password.update');
Route::get('employee/update/{id}','HomeController@employee')->name('employee.password');
Route::PATCH('employee/reset/{id}','HomeController@password')->name('employee.password.update');

app/Http/Controllers/PeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Physicalexamination;
use Illuminate\Http\Request;
use Auth;
use App\Models\ActivityLog;
class PeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('pe.create')->with('id',$id);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$id )
    {
        $request->validate([
            'skin' => 'required',
            'neck' => 'required',
            'pupils' => 'required',
            'ears' => 'required',
            'nose' => 'required',
            'mouth' => 'required',
            'thyroid' => 'required',
            'chest' => 'required',
            'lungs' => 'required',
            'heart' => 'required',
            'abdomen' => 'required',
            'back' => 'required',
            'anus' => 'required',
            'gusystem' => 'required',
            'inguinals' => 'required',
            'reflexes' => 'required',
            'extremities' => 'required'
        ]);
        $patient = new Physicalexamination;
        $patient->information_id = $id;
        $patient->skin = $request->skin;
        $patient->neck = $request->neck;
        $patient->pupils = $request->pupils;
        $patient->ears = $request->ears;
        $patient->nose = $request->nose;
        $patient->mouth = $request->mouth;
        $patient->thyroid = $request->thyroid;
        $patient->chest = $request->chest;
        $patient->lungs = $request->lungs;
        $patient->heart = $request->heart;
        $patient->abdomen = $request->abdomen;
        $patient->back = $request->back;
        $patient->anus = $request->anus;
        $patient->gusystem = $request->gusystem;
        $patient->inguinals = $request->inguinals;
        $patient->reflexes = $request->reflexes;
        $patient->extremities = $request->extremities;
        $patient->save();
        ActivityLog::create(['user_id' => Auth::user()->id, 'action' => 'Created a physicalexamination for patient '.$id]);
        return redirect()->route('patients')->With('status','Physical Examination record for patient '.$id.' added');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Physicalexamination  $physicalexamination
     * @return \Illuminate\Http\Response
     */
    public function show(Physicalexamination $physicalexamination)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Physicalexamination  $physicalexamination
     * @return \Illuminate\Http\Response
     */
    public function edit(Physicalexamination $physicalexamination,$id)
    {
        $physicalexamination = Physicalexamination::where('information_id',$id)->first();
        return view('pe.edit')->with(['patient' => $physicalexamination]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Physicalexamination  $physicalexamination
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Physicalexamination $physicalexamination,$id)
    {
        $request->validate([
            'skin' => 'required',
            'neck' => 'required',
            'pupils' => 'required',
            'ears' => 'required',
            'nose' => 'required',
            'mouth' => 'required',
            'thyroid' => 'required',
            'chest' => 'required',
            'lungs' => 'required',
            'heart' => 'required',
            'abdomen' => 'required',
            'back' => 'required',
            'anus' => 'required',
            'gusystem' => 'required',
            'inguinals' => 'required',
            'reflexes' => 'required',
            'extremities' => 'required'
        ]);
        $physicalexamination = Physicalexamination::find($id);
        $physicalexamination->skin = $request->skin;
        $physicalexamination->neck = $request->neck;
        $physicalexamination->pupils = $request->pupils;
        $physicalexamination->ears = $request->ears;
        $physicalexamination->nose = $request->nose;
        $physicalexamination->mouth = $request->mouth;
        $physicalexamination->thyroid = $request->thyroid;
        $physicalexamination->chest = $request->chest;
        $physicalexamination->lungs = $request->lungs;
        $physicalexamination->heart = $request->heart;
        $physicalexamination->abdomen = $request->abdomen;
        $physicalexamination->back = $request->back;
        $physicalexamination->anus = $request->anus;
        $physicalexamination->gusystem = $request->gusystem;
        $physicalexamination->inguinals = $request->inguinals;
        $physicalexamination->reflexes = $request->reflexes;
        $physicalexamination->extremities = $request->extremities;
        $physicalexamination->save();
        ActivityLog::create(['user_id' => Auth::user()->id, 'action' => 'Updated a physicalexamination for patient '.$id]);
        return redirect()->back()->with('status','Updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Physicalexamination  $physicalexamination
     * @return \Illuminate\Http\Response
     */
    public function destroy(Physicalexamination $physicalexamination)
    {
        //
    }
}

resources/views/pe/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-dark mt-3">
		<div class="card-header">Physical Examination of Patient {{ $id }}</div>
		<div class="card-body">
			@include('shared.alerts')
			<form method = "POST" action="{{ route('phyexam.store',['id' => $id] ) }}">
				{{ csrf_field()}}
				<div class="row">
			      <div class="col-md-6 mb-2">
			        <div class="row">
			          <div class="col-md-5 mb-2">
			            <label for="skin">Skin</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="skin" name="skin" value="{{ old('skin') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="neck">Neck, Head, Scalp</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="neck" name="neck" value="{{ old('neck') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="pupils">Pupils, Optalmoscopic</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="pupils" name="pupils" value="{{ old('pupils') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="ears">Ears</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="ears" name="ears" value="{{ old('ears') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for='nose'>Nose, Sinuses</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="nose" name="nose" value="{{ old('nose') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="mouth">Mouth, Throat</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="mouth" name="mouth" value="{{ old('mouth') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="thyroid">Neck, L.N., Thyroid</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="thyroid" name="thyroid" value="{{ old('thyroid') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="chest">Chest, Breast, Axilla</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="chest" name="chest" value="{{ old('chest') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="lungs">Lungs</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="lungs" name="lungs" value="{{ old('lungs') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="heart">Heart</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="heart" name="heart" value="{{ old('heart') }}">
			          </div><!--col-md-8-->
			        </div><!--row-->
			      </div><!--col-md-6-->
			      <div class="col-md-6 mb-2">
			        <div class="row">
			          <div class="col-md-5 mb-2">
			            <label for="abdomen">Abdomen</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="abdomen" name="abdomen" value="{{ old('abdomen') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="Back">Back</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="Back" name="back" value="{{ old('back') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="anus">Anus, Rectum</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="anus" name="anus" value="{{ old('anus') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="gusystem">G-U System</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="gusystem" name="gusystem" value="{{ old('gusystem') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="inguinals">Inguinals, Genitals</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="inguinals" name="inguinals" value="{{ old('inguinals') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="reflexes">Reflexes</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="reflexes" name="reflexes" value="{{ old('reflexes') }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="extremities">Extremities</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="extremities" name="extremities" value="{{ old('extremities') }}">
			          </div><!--col-md-8-->
			        </div><!--row-->
			      </div><!--col-md-6-->
			    </div><!--row-->
			  	<div class="row">
			  		<button class="btn btn-info ml-2">Save</button>
			  	</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/pe/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-dark mt-3">
		<div class="card-header">Update Physical Examination of Patient {{ $patient->id }}</div>
		<div class="card-body">
			@include('shared.alerts')
			<form method = "POST" action="{{ route('phyexam.update',['id' => $patient->id] ) }}">
				{{ csrf_field()}}
				{{ method_field('patch') }}
				<div class="row">
			      <div class="col-md-6 mb-2">
			        <div class="row">
			          <div class="col-md-5 mb-2">
			            <label for="skin">Skin</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="skin" name="skin" value="{{ $patient->skin }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="neck">Neck, Head, Scalp</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="neck" name="neck" value="{{ $patient->neck }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="pupils">Pupils, Optalmoscopic</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="pupils" name="pupils" value="{{ $patient->pupils }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="ears">Ears</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="ears" name="ears" value="{{ $patient->ears }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for='nose'>Nose, Sinuses</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="nose" name="nose" value="{{ $patient->nose }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="mouth">Mouth, Throat</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="mouth" name="mouth" value="{{ $patient->mouth }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="thyroid">Neck, L.N., Thyroid</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="thyroid" name="thyroid" value="{{ $patient->thyroid }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="chest">Chest, Breast, Axilla</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="chest" name="chest" value="{{ $patient->chest  }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="lungs">Lungs</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="lungs" name="lungs" value="{{ $patient->lungs  }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="heart">Heart</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="heart" name="heart" value="{{ $patient->heart }}">
			          </div><!--col-md-8-->
			        </div><!--row-->
			      </div><!--col-md-6-->
			      <div class="col-md-6 mb-2">
			        <div class="row">
			          <div class="col-md-5 mb-2">
			            <label for="abdomen">Abdomen</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="abdomen" name="abdomen" value="{{ $patient->abdomen }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="Back">Back</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="Back" name="back" value="{{ $patient->back }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="anus">Anus, Rectum</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="anus" name="anus" value="{{ $patient->anus }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="gusystem">G-U System</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="gusystem" name="gusystem" value="{{ $patient->gusystem }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="inguinals">Inguinals, Genitals</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="inguinals" name="inguinals" value="{{ $patient->inguinals }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="reflexes">Reflexes</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="reflexes" name="reflexes" value="{{ $patient->reflexes  }}">
			          </div><!--col-md-8-->
			          <div class="col-md-5 mb-2">
			            <label for="extremities">Extremities</label>
			          </div><!--col-md-4-->
			          <div class="col-md-7 mb-2">
			            <input type="text" class="form-control" id="extremities" name="extremities" value="{{ $patient->extremities  }}">
			          </div><!--col-md-8-->
			        </div><!--row-->
			      </div><!--col-md-6-->
			    </div><!--row-->
			  	<div class="row">
			  		<button class="btn btn-info ml-2">Save</button>
			  	</div>
			</form>
		</div>
	</div>
</div>
@endsection