routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login');

Auth::routes();

Route::get('patients','HomeController@patients')->middleware('doctor')->name('patients');
Route::get('labrep','HomeController@lab')->middleware('labtech')->name('labtech');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('print/{id}',"HomeController@print")->name('print');

Route::resource('users','UserController')->middleware('admin');

Route::resource('information','informationController')->except(['destroy'])->middleware('nurse');

Route::name('vitalsign.')->prefix('vitalsign/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});

Route::name('phyexam.')->prefix('phyexam/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','PeController@create')->name('create');
	Route::post('store/{id}','PeController@store')->name('store');
	Route::get('edit/{id}','PeController@edit')->name('edit');
	Route::patch('update/{id}','PeController@update')->name('update');
});

Route::name('dental.')->prefix('dental/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','DentalController@create')->name('create');
	Route::post('store/{id}','DentalController@store')->name('store');
	Route::get('edit/{id}','DentalController@edit')->name('edit');
	Route::patch('update/{id}','DentalController@update')->name('update');
});

Route::name('labreport.')->prefix('lab/')->middleware('labtech')->group(function(){
	Route::get('create/{id}','LabReportController@create')->name('create');
	Route::post('store/{id}','LabReportController@store')->name('store');
	Route::get('edit/{id}','LabReportController@edit')->name('edit');
	Route::patch('update/{id}','LabReportController@update')->name('update');
	Route::view('upload/{id}','lab/upload')->name('upload');
});
Route::name('feedback.')->prefix('final')->middleware('doctor')->group(function(){
	Route::get('create/{id}','FeedbackController@create')->name('create');
	Route::post('store/{id}','FeedbackController@store')->name('store');
	// Route::get('edit/{id}','DentalController@edit')->name('edit');
	// Route::patch('update/{id}','DentalController@update')->name('update');
});
Route::get('labresult/{id}','LabReportController@edit')->middleware('doctor')->name('labresult.view');
Route::patch('labresult/{id}','LabReportController@update')->middleware('doctor')->name('labresult.update');


	Route::get('upload','LabReportController@upload_view')->name('upload');
	Route::get('upload/{id}','LabReportController@select')->middleware('labtech')->name('upload.edit');
	Route::get('search/{id}/upload','LabReportController@viewImage')->name('upload.search');
	Route::post('upload/{id}/save','LabReportController@saveimage')->middleware('labtech')->name('upload.save');
Route::get('admin/patients','UserController@patients')->middleware('admin')->name('patients.admin');
Route::get('admin/patient/delete/{id}','UserController@deletePatient')->middleware('admin')->name('admin.delete');
Route::get('admin/logs','HomeController@logs')->middleware('admin')->name('logs');
Route::get('settings','HomeController@view_settings')->name('settings');
Route::PATCH('password/update/{id}','HomeController@password')->name('password.update');
Route::get('employee/update/{id}','HomeController@employee')->name('employee.password');
Route::PATCH('employee/reset/{id}','HomeController@password')->name('employee.password.update');

app/Models/Vitalsign.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Vitalsign extends Model
{
    //
}

app/Http/Controllers/VitalSignController.php
<?php

namespace App\Http\Controllers;

use App\Models\Vitalsign;
use Illuminate\Http\Request;
use Auth;
use App\Models\ActivityLog;
class VitalSignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        // dd($id);
        return view('vitalsign.create')->with(['id' => $id]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$id)
    {
        $request->validate([
            'height' => 'required',
            'weight' => 'required',
            'bp'     => 'required',
            'pulse' => 'required',
            'respiration' => 'required',
            'bmi' => 'required',
            'ppd' => 'required',
            'mmr' => 'required',
            'bodybuilt' => 'required',
            'lmp' => 'nullable',
            'lsc' => 'nullable',
            'method' => 'nullable',
            'uc_fv_od' => 'required|integer',
            'uc_fv_os' => 'required|integer',
            'c_fv_od' => 'required|integer',
            'c_fv_os' => 'required|integer',
            'uc_nv_od' => 'required|integer',
            'uc_nv_os' => 'required|integer',
            'c_nv_od' => 'required|integer',
            'c_nv_os' => 'required|integer',
            'optical' => 'required|boolean',
            'colorvision' => 'required|boolean',
            'ad' => 'required|integer',
            'as' => 'required|integer'
        ]);
        $patient = new Vitalsign;
        $patient->information_id = $id;
        $patient->height = $request->height;
        $patient->weight = $request->weight;
        $patient->bp = $request->bp;
        $patient->pulse = $request->pulse;
        $patient->respiration = $request->respiration;
        $patient->bmi = $request->bmi;
        $patient->ppd = $request->ppd;
        $patient->lmp = $request->lmp;
        $patient->lsc = $request->lsc;
        $patient->bodybuilt = $request->bodybuilt;
        $patient->mmr = $request->mmr;
        $patient->method = $request->method;
        $patient->uncorrected_fv_od = $request->uc_fv_od;
        $patient->unccorected_fv_os = $request->uc_fv_os;
        $patient->uncorrected_nv_od = $request->uc_nv_od;
        $patient->unccorected_nv_os = $request->uc_nv_os;
        $patient->corrected_fv_od = $request->c_fv_od;
        $patient->corrected_fv_os = $request->c_fv_os;
        $patient->corrected_nv_od = $request->c_nv_od;
        $patient->corrected_nv_os = $request->c_nv_os;
        $patient->optical = $request->optical;
        $patient->colorvision = $request->colorvision;
        $patient->as = $request->as;
        $patient->ad = $request->ad;
        $patient->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Created a vital sign information for patient '.$id]);
        return redirect()->route('patients')->with('status','Successfully added a vital sign to patient '.$id);
    }   

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Vitalsign  $vitalsign
     * @return \Illuminate\Http\Response
     */
    public function show(Vitalsign $vitalsign)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Vitalsign  $vitalsign
     * @return \Illuminate\Http\Response
     */
    public function edit(Vitalsign $vitalsign,$id)
    {
        $vitalsign = Vitalsign::where('information_id',$id)->first();
        return view('vitalsign.edit')->with('vitals',$vitalsign);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Vitalsign  $vitalsign
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vitalsign $vitalsign,$id)
    {
        $request->validate([
            'height' => 'required',
            'weight' => 'required',
            'bp'     => 'required',
            'pulse' => 'required',
            'respiration' => 'required',
            'bmi' => 'required',
            'ppd' => 'required',
            'mmr' => 'required',
            'bodybuilt' => 'required',
            'lmp' => 'nullable',
            'lsc' => 'nullable',
            'method' => 'nullable',
            'uc_fv_od' => 'required|integer',
            'uc_fv_os' => 'required|integer',
            'c_fv_od' => 'required|integer',
            'c_fv_os' => 'required|integer',
            'uc_nv_od' => 'required|integer',
            'uc_nv_os' => 'required|integer',
            'c_nv_od' => 'required|integer',
            'c_nv_os' => 'required|integer',
            'optical' => 'required|boolean',
            'colorvision' => 'required|boolean',
            'ad' => 'required|integer',
            'as' => 'required|integer'
        ]);
        $vitalsign = Vitalsign::find($id);
        $vitalsign->height = $request->height;
        $vitalsign->weight = $request->weight;
        $vitalsign->bp = $request->bp;
        $vitalsign->pulse = $request->pulse;
        $vitalsign->respiration = $request->respiration;
        $vitalsign->bmi = $request->bmi;
        $vitalsign->ppd = $request->ppd;
        $vitalsign->lmp = $request->lmp;
        $vitalsign->lsc = $request->lsc;
        $vitalsign->bodybuilt = $request->bodybuilt;
        $vitalsign->mmr = $request->mmr;
        $vitalsign->method = $request->method;
        $vitalsign->uncorrected_fv_od = $request->uc_fv_od;
        $vitalsign->unccorected_fv_os = $request->uc_fv_os;
        $vitalsign->uncorrected_nv_od = $request->uc_nv_od;
        $vitalsign->unccorected_nv_os = $request->uc_nv_os;
        $vitalsign->corrected_fv_od = $request->c_fv_od;
        $vitalsign->corrected_fv_os = $request->c_fv_os;
        $vitalsign->corrected_nv_od = $request->c_nv_od;
        $vitalsign->corrected_nv_os = $request->c_nv_os;
        $vitalsign->optical = $request->optical;
        $vitalsign->colorvision = $request->colorvision;
        $vitalsign->as = $request->as;
        $vitalsign->ad = $request->ad;
        $vitalsign->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Updated a vital sign information for patient '.$id]);
        return redirect()->route('patients')->with('status','Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Vitalsign  $vitalsign
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vitalsign $vitalsign)
    {
        //
    }
}

resources/views/vitalsign/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-info mt-3">
		<div class="card-header">Vital Sign</div>
		<div class="card-body">
			<form method="POST" action="{{ route('vitalsign.store',['id' => $id]) }}">
				@include('shared.alerts')
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="height">Height:</label>
					    <input type="text" class="form-control" id="height" name="height" value="{{ old('height') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="weight">Weight:</label>
					    <input type="text" class="form-control" id="weight" name="weight" value="{{ old('weight') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="bp">BP:</label>
					    <input type="text" class="form-control" id="bp" name="bp" value="{{ old('bp') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">Pulse:</label>
					    <input type="text" class="form-control" id="pulse" name="pulse" value="{{ old('pulse') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="respiration">Respiration:</label>
					    <input type="text" class="form-control" id="respiration" name="respiration" value="{{ old('respiration') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">BMI:</label>
					    <input type="text" class="form-control" id="bmi" name="bmi" value="{{ old('bmi') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ppd">PPD:</label>
					    <input type="text" class="form-control" id="ppd" name="ppd" value="{{ old('ppd') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="mmr">MMR:</label>
					    <input type="text" class="form-control" id="mmr" name="mmr" value="{{ old('mmr') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="bodybuilt">Body Built:</label>
					    <input type="text" class="form-control" id="bodybuilt" name="bodybuilt" value="{{ old('bodybuilt') }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lmp">L.M.P:</label>
					    <input type="text" class="form-control" id="lmp" name="lmp" value="{{ old('lmp') }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lsc">L.S.C:</label>
					    <input type="text" class="form-control" id="lsc" name="lsc" value="{{ old('lsc') }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="method">Method:</label>
					    <input type="text" class="form-control" id="method" name="method" value="{{ old('method') }}">
					</div>
				</div>
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_od">Uncorrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="uc_fv_od" name="uc_fv_od" value="{{ old('uc_fv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_os">Uncorrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="uc_fv_os" name="uc_fv_os" value="{{ old('uc_fv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_od">Corrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="c_fv_od" name="c_fv_od" value="{{ old('c_fv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_os">Corrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="c_fv_os" name="c_fv_os" value="{{ old('c_fv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_od">Uncorrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="uc_nv_od" name="uc_nv_od" value="{{ old('uc_nv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_os">Uncorrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="uc_nv_os" name="uc_nv_os" value="{{ old('uc_nv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_od">Corrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="c_nv_od" name="c_nv_od" value="{{ old('c_nv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_os">Corrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="c_nv_os" name="c_nv_os" value="{{ old('c_nv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="optical">Optical:</label>
					   	<select class="form-control" name="optical" id="optical">
					   		<option value="0">For Opto Clearance</option>
					   		<option value="1">Cleared</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="colorvision">Color Vision:</label>
					    <select class="form-control" name="colorvision" id="colorvision">
					   		<option value="0">Defective</option>
					   		<option value="1">Adequate</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ad">Hearing AD:</label>
					    <input type="text" class="form-control" id="ad" name="ad" value="{{ old('ad') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="as">Hearing AS:</label>
					    <input type="text" class="form-control" id="as" name="as" value="{{ old('as') }}">
					</div>
				</div>
				<div class="row">
					<div class="form-group col-12 col-sm-2">
						{{ csrf_field() }}
					    <button class="btn btn-info">Save</button>
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/vitalsign/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
		<div class="card card-info mt-3">
		<div class="card-header">Vital Sign of Patient {{ $vitals->information_id }}</div>
		<div class="card-body">
			<form method="POST" action="{{ route('vitalsign.update',['id' => $vitals->id]) }}">

				{{csrf_field()}} {{ method_field('patch') }}
				@include('shared.alerts')
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="height">Height:</label>
					    <input type="text" class="form-control" id="height" name="height" value="{{ $vitals->height }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="weight">Weight:</label>
					    <input type="text" class="form-control" id="weight" name="weight" value="{{ $vitals->weight }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="bp">BP:</label>
					    <input type="text" class="form-control" id="bp" name="bp" value="{{ $vitals->bp }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">Pulse:</label>
					    <input type="text" class="form-control" id="pulse" name="pulse" value="{{ $vitals->pulse }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="respiration">Respiration:</label>
					    <input type="text" class="form-control" id="respiration" name="respiration" value="{{ $vitals->respiration }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">BMI:</label>
					    <input type="text" class="form-control" id="bmi" name="bmi" value="{{ $vitals->bmi }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ppd">PPD:</label>
					    <input type="text" class="form-control" id="ppd" name="ppd" value="{{ $vitals->ppd }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="mmr">MMR:</label>
					    <input type="text" class="form-control" id="mmr" name="mmr" value="{{ $vitals->mmr }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="bodybuilt">Body Built:</label>
					    <input type="text" class="form-control" id="bodybuilt" name="bodybuilt" value="{{ $vitals->bodybuilt }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lmp">L.M.P:</label>
					    <input type="text" class="form-control" id="lmp" name="lmp" value="{{ $vitals->lmp }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lsc">L.S.C:</label>
					    <input type="text" class="form-control" id="lsc" name="lsc" value="{{ $vitals->lsc }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="method">Method:</label>
					    <input type="text" class="form-control" id="method" name="method" value="{{ $vitals->method }}">
					</div>
				</div>
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_od">Uncorrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="uc_fv_od" name="uc_fv_od" value="{{ $vitals->uncorrected_fv_od }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_os">Uncorrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="uc_fv_os" name="uc_fv_os" value="{{ $vitals->unccorected_fv_os }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_od">Corrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="c_fv_od" name="c_fv_od" value="{{ $vitals->corrected_fv_od }}">
					</div>
					{{-- {{ dd($vitals)}} --}}
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_os">Corrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="c_fv_os" name="c_fv_os" value="{{ $vitals->corrected_fv_os }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_od">Uncorrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="uc_nv_od" name="uc_nv_od" value="{{ $vitals->uncorrected_nv_od }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_os">Uncorrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="uc_nv_os" name="uc_nv_os" value="{{ $vitals->unccorected_nv_os }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_od">Corrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="c_nv_od" name="c_nv_od" value="{{ $vitals->corrected_nv_od }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_os">Corrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="c_nv_os" name="c_nv_os" value="{{ $vitals->corrected_nv_os}}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="optical">Optical:</label>
					   	<select class="form-control" name="optical" id="optical">
					   		<option value="0" @if($vitals->optical == 0) selected @endif>For Opto Clearance</option>
					   		<option value="1" @if($vitals->optical == 1) selected @endif>Cleared</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="colorvision">Color Vision:</label>
					    <select class="form-control" name="colorvision" id="colorvision">
					   		<option value="0" @if($vitals->colorvision == 0) selected @endif>Defective</option>
					   		<option value="1" @if($vitals->colorvision == 1) selected @endif>>Adequate</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ad">Hearing AD:</label>
					    <input type="text" class="form-control" id="ad" name="ad" value="{{ $vitals->ad }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="as">Hearing AS:</label>
					    <input type="text" class="form-control" id="as" name="as" value="{{ $vitals->as }}">
					</div>
				</div>
				<div class="row">
					<div class="form-group col-12 col-sm-2">
						{{ csrf_field() }}
					    <button class="btn btn-info">Save</button>
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection