routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login');

Auth::routes();

Route::get('patients','HomeController@patients')->middleware('doctor')->name('patients');
Route::get('labrep','HomeController@lab')->middleware('labtech')->name('labtech');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('print/{id}',"HomeController@print")->name('print');

Route::resource('users','UserController')->middleware('admin');

Route::resource('information','informationController')->except(['destroy'])->middleware('nurse');

Route::name('vitalsign.')->prefix('vitalsign/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});

Route::name('phyexam.')->prefix('phyexam/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','PeController@create')->name('create');
	Route::post('store/{id}','PeController@store')->name('store');
	Route::get('edit/{id}','PeController@edit')->name('edit');
	Route::patch('update/{id}','PeController@update')->name('update');
});

Route::name('dental.')->prefix('dental/')->middleware('doctor')->group(function(){
	Route::get('create/{id}','DentalController@create')->name('create');
	Route::post('store/{id}','DentalController@store')->name('store');
	Route::get('edit/{id}','DentalController@edit')->name('edit');
	Route::patch('update/{id}','DentalController@update')->name('update');
});

Route::name('labreport.')->prefix('lab/')->middleware('labtech')->group(function(){
	Route::get('create/{id}','LabReportController@create')->name('create');
	Route::post('store/{id}','LabReportController@store')->name('store');
	Route::get('edit/{id}','LabReportController@edit')->name('edit');
	Route::patch('update/{id}','LabReportController@update')->name('update');
	Route::view('upload/{id}','lab/upload')->name('upload');
});
Route::name('feedback.')->prefix('final')->middleware('doctor')->group(function(){
	Route::get('create/{id}','FeedbackController@create')->name('create');
	Route::post('store/{id}','FeedbackController@store')->name('store');
	// Route::get('edit/{id}','DentalController@edit')->name('edit');
	// Route::patch('update/{id}','DentalController@update')->name('update');
});
Route::get('labresult/{id}','LabReportController@edit')->middleware('doctor')->name('labresult.view');
Route::patch('labresult/{id}','LabReportController@update')->middleware('doctor')->name('labresult.update');


	Route::get('upload','LabReportController@upload_view')->name('upload');
	Route::get('upload/{id}','LabReportController@select')->middleware('labtech')->name('upload.edit');
	Route::get('search/{id}/upload','LabReportController@viewImage')->name('upload.search');
	Route::post('upload/{id}/save','LabReportController@saveimage')->middleware('labtech')->name('upload.save');
Route::get('admin/patients','UserController@patients')->middleware('admin')->name('patients.admin');
Route::get('admin/patient/delete/{id}','UserController@deletePatient')->middleware('admin')->name('admin.delete');
Route::get('admin/logs','HomeController@logs')->middleware('admin')->name('logs');
Route::get('settings','HomeController@view_settings')->name('settings');
Route::PATCH('password/update/{id}','HomeController@password')->name('password.update');
Route::get('employee/update/{id}','HomeController@employee')->name('employee.password');
Route::PATCH('employee/reset/{id}','HomeController@password')->name('employee.password.update');

resources/views/employees/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-8 col-xs-12 col-12 mx-auto">
			<div class="card border-dark mt-4">
			  <div class="card-header">Employees
			  	<a href="{{ route('users.index') }}" class="btn btn-primary btn-sm mr-auto float-right">
					Back
				</a>
				</div>
				<div class="card-body">
					@include('shared.alerts')
					<form method="POST" action="{{ route('users.store') }}">
						{{ csrf_field() }}
						<div class="row">
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="name" class="form-control-label">Fullname:</label>
								<input type="text"  class="form-control" id="name" name="name" value="{{ old('name') }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="email" class="form-control-label">Emailaddress:</label>
								<input type="text"  class="form-control" id="email" name="email" value="{{ old('email') }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="role" class="form-control-label">Role:</label>
								<select  id="role" name="role" class="form-control">
									@foreach($roles as $role)
										<option value="{{ $role->id}}" @if(old('role') == $role->id) selected @endif>{{ $role->role }}</option>
									@endforeach
								</select>
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="licensenumber" class="form-control-label">License Number:</label>
								<input type="text"  class="form-control" id="licensenumber" name="licensenumber" value="{{ old('licensenumber') }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="password" class="form-control-label">Password:</label>
								<input type="password"  class="form-control" id="password" name="password">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="password_confirmation" class="form-control-label">Confirm Password:</label>
								<input type="password"  class="form-control" id="password_confirmation" name="password_confirmation">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12 mt-3">
								<button class="btn btn-info">Save</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/employees/delete.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-8 col-xs-12 col-12 mx-auto">
			<div class="card border-dark mt-4">
			  <div class="card-header">Employees
			  	<a href="{{ route('users.index') }}" class="btn btn-primary btn-sm mr-auto float-right">
					Back
				</a>
				</div>
				<div class="card-body">
					@include('shared.alerts')
					<form method="POST" action="{{ route('users.update',['id' => $user->id]) }}">
						{{ method_field('DELETE') }}
						{{ csrf_field() }}
						<div class="row">
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="name" class="form-control-label">Fullname:</label>
								<input type="text"  class="form-control" id="name" name="name" value="{{ $user->name }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="email" class="form-control-label">Emailaddress:</label>
								<input type="text"  class="form-control" id="email" name="email" value="{{ $user->email }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="role" class="form-control-label">Role:</label>
								<select  id="role" name="role" class="form-control">
									@foreach($roles as $role)
										<option value="{{ $role->id}}" @if($user->role_id == $role->id) selected @endif>{{ $role->role }}</option>
									@endforeach
								</select>
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="licensenumber" class="form-control-label">License Number:</label>
								<input type="text"  class="form-control" id="licensenumber" name="licensenumber" value="{{ $user->licensenumber }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12 mt-3">
								<button href="{{ route('users.edit',['id' => $user->id]) }}" class="btn btn-info">Update</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-8 col-xs-12 col-12 mx-auto">
			<div class="card border-dark mt-4">
			  <div class="card-header">Employees
			  	<a href="{{ route('users.index') }}" class="btn btn-primary btn-sm mr-auto float-right">
					Back
				</a>
				</div>
				<div class="card-body">
					@include('shared.alerts')
					<form method="POST" action="{{ route('users.update',['id' => $user->id]) }}">
						{{ method_field('PATCH') }}
						{{ csrf_field() }}
						<div class="row">
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="name" class="form-control-label">Fullname:</label>
								<input type="text"  class="form-control" id="name" name="name" value="{{ $user->name }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="email" class="form-control-label">Emailaddress:</label>
								<input type="text"  class="form-control" id="email" name="email" value="{{ $user->email }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="role" class="form-control-label">Role:</label>
								<select  id="role" name="role" class="form-control">
									@foreach($roles as $role)
										<option value="{{ $role->id}}" @if($user->role_id == $role->id) selected @endif>{{ $role->role }}</option>
									@endforeach
								</select>
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="licensenumber" class="form-control-label">License Number:</label>
								<input type="text"  class="form-control" id="licensenumber" name="licensenumber" value="{{ $user->licensenumber }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12 mt-3">
								<button href="{{ route('users.edit',['id' => $user->id]) }}" class="btn btn-info">Update</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-dark mt-4">
	  <div class="card-header">Employees
	  	<a href="{{ route('users.create') }}" class="btn btn-primary btn-sm mr-auto float-right">
			New Employee
		</a>
	</div>
	  <div class="card-body text-dark">
		<table class="table " id="myTable" >
		  <thead class="thead-inverse card-text">
		      <th>#</th>
		      <th>Name</th>
		      <th>Email</th>
		      <th>Role</th>
  		      <th>Action</th>
		      <th>Date Created</th>
		  </thead>
		  <tbody>
		    @include('shared.alerts')
		    @foreach($users as $user)
		    <tr>
		      	<td>{{ $user->id }}</td>
		      	<td>{{ $user->name }}</td>
			    <td>{{ $user->email }}</td>	
			    <td>{{ $user->roles->role }}</td>
			    <td>
					<a href="{{ route('users.show',['id' => $user->id]) }}" class="btn btn-info btn-sm"><i class="fa fa-search"></i></a>
					<a href="{{ route('users.edit',['id' => $user->id]) }}" class="btn btn-warning btn-sm"><i class="fa fa-pencil"></i> </a>
					<a href="{{ route('employee.password',['id'=> $user->id]) }}" class="btn btn-info btn-sm"><i class="fa fa-key" aria-hidden="true"></i>
					</a>
					<form method='POST' action ="{{ route('users.destroy',[ 'id' => $user->id ]) }}" style="display: inline-block;">
						{{ csrf_field() }} {{ method_field('DELETE') }} 
						<button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
					</form>
			    </td>
			    <td>{{ $user->created_at->format('m-d-Y') }}</td>
		    </tr>
		    @endforeach
		  </tbody>
		</table>
	  </div>
</div>
</div>
@endsection

resources/views/employees/view.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-8 col-xs-12 col-12 mx-auto">
			<div class="card border-dark mt-4">
			  <div class="card-header">Employees
			  	<a href="{{ route('users.index') }}" class="btn btn-primary btn-sm mr-auto float-right">
					Back
				</a>
				</div>
				<div class="card-body">
{{-- 					<form method="POST" action="{{ route('users.update',['id' => $user->id]) }}">
						{{ method_field('PATCH') }}
						{{ csrf_field() }} --}}
						@include('shared.alerts')
						<div class="row">
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="name" class="form-control-label">Fullname:</label>
								<input type="text" readonly class="form-control" id="name" name="name" value="{{ $user->name }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="email" class="form-control-label">Emailaddress:</label>
								<input type="text" readonly class="form-control" id="email" name="email" value="{{ $user->email }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="role" class="form-control-label">Role:</label>
								<select readonly id="role" name="role" class="form-control">
									@foreach($roles as $role)
										<option value="{{ $role->id}}" @if($user->role_id == $role->id) selected @endif>{{ $role->role }}</option>
									@endforeach
								</select>
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12">
								<label for="licensenumber" class="form-control-label">License Number:</label>
								<input type="text" readonly class="form-control" id="licensenumber" name="licensenumber" value="{{ $user->licensenumber }}">
							</div> 
							<div class="col-12 col-sm-12 col-md-12 col-lg-12 mt-3">
								<a href="{{ route('users.edit',['id' => $user->id]) }}" class="btn btn-info">Update</a>
							</div>
						</div>
					{{-- </form> --}}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection